[package]
name = "ft_kalman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graplot = "0.1.22"
plotpy = "0.5.1"
plotters = "0.3.5"
